Update DominionGirl.py
Added dictionaries. 
Error message: 
"Traceback (most recent call last):
  File "dominiongirl.py", line 74, in <module>
    print give10(deck)
  File "dominiongirl.py", line 32, in give10
    del unshuffled_list[r]
TypeError: 'str' object doesn't support item deletion"